"""unique constraint

Revision ID: c2ba62408b75
Revises: 7f84efe3eb9c
Create Date: 2026-05-12 12:24:49.949366

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c2ba62408b75"
down_revision: Union[str, Sequence[str], None] = "7f84efe3eb9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "item", ["text"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "item", type_="unique")
    # ### end Alembic commands ###
